# 1. Acquire the base image
FROM ros:noetic-ros-base

# 2. Install packages
RUN apt-get update && \
    apt-get install -y ros-noetic-turtlesim

# 3. Configure execution (`entrypoint`, `command`)
# RUN echo "source /opt/ros/foxy/setup.bash" >> ~/.bashrc
CMD ["tail", "-f", "/dev/null"]
