
services:

    floor_demo:
        image: galactic_floor_demo
        container_name: floor_demo
        networks:
            - ros-tutorial-network
        build:
            context: .
            dockerfile: ./dockerfile
        environment:
            - "DISPLAY=novnc:0.0"


networks:
    ros-tutorial-network:
        name: ros-tutorial-network
        driver: bridge
        external: true