
version: '2.17.2'

services:

    novnc:
        image: theasp/novnc:latest
        container_name: novnc
        networks:
            - ros
        environment:
            - "DISPLAY_WIDTH=1920"
            - "DISPLAY_HEIGHT=1080"
            - "RUN_XTERM=no"
        ports:
            - "1348:8080"

    floor_demo:
        image: humble_floor_demo
        container_name: floor_demo
        networks:
            - ros
        build:
            context: .
            dockerfile: ./dockerfile
        environment:
            - "DISPLAY=novnc:0.0"


networks:
    ros:
        driver: bridge