# 1. Acquire the base image
FROM osrf/ros:humble-desktop

# 2. Install packages
RUN apt-get update && \
    apt-get install -y ros-humble-turtlesim

# 3. Configure execution (`entrypoint`, `command`)
RUN echo "source /opt/ros/humble/setup.bash" >> ~/.bashrc
CMD ["tail", "-f", "/dev/null"]
