
version: '2.17.2'

services:

    turtlesim:
        image: humble_turtlesim
        container_name: turtlesim
        networks:
            - ros-tutorial-network
        build:
            context: .
            dockerfile: ./dockerfile
        environment:
            - "DISPLAY=novnc:0.0"
        command: >
            bash -c "
                ros2 run turtlesim turtlesim_node
            "


networks:
    ros-tutorial-network:
        name: ros-tutorial-network
        driver: bridge
        external: true