
version: '2.17.2'

services:

    novnc:
        image: theasp/novnc:latest
        container_name: novnc
        networks:
            - ros
        environment:
            - "DISPLAY_WIDTH=1280"
            - "DISPLAY_HEIGHT=1024"
            - "RUN_XTERM=no"
        ports:
            - "1348:8080"

    turtlesim:
        image: humble_turtlesim
        container_name: turtlesim
        networks:
            - ros
        build:
            context: .
            dockerfile: ./dockerfile
        environment:
            - "QT_X11_NO_MITSHM=1" #fix some QT bugs
            - "DISPLAY=novnc:0.0"
        command: >
            bash -c "
                ros2 run turtlesim turtlesim_node
            "


networks:
    ros:
        driver: bridge